// Code generated by dagger-compiler.  Do not edit.
package com.paylogic.scanwarelite.helpers;

import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<ConnectivityHelper>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code ConnectivityHelper} and its
 * dependencies.
 *
 * Being a {@code Provider<ConnectivityHelper>} and handling creation and
 * preparation of object instances.
 */
public final class ConnectivityHelper$$InjectAdapter extends Binding<ConnectivityHelper>
    implements Provider<ConnectivityHelper> {
  private Binding<android.content.Context> context;

  public ConnectivityHelper$$InjectAdapter() {
    super("com.paylogic.scanwarelite.helpers.ConnectivityHelper", "members/com.paylogic.scanwarelite.helpers.ConnectivityHelper", NOT_SINGLETON, ConnectivityHelper.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    context = (Binding<android.content.Context>) linker.requestBinding("android.content.Context", ConnectivityHelper.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(context);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<ConnectivityHelper>}.
   */
  @Override
  public ConnectivityHelper get() {
    ConnectivityHelper result = new ConnectivityHelper(context.get());
    return result;
  }

}
