// Code generated by dagger-compiler.  Do not edit.
package com.paylogic.scanwarelite.helpers;

import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<PreferenceHelper>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code PreferenceHelper} and its
 * dependencies.
 *
 * Being a {@code Provider<PreferenceHelper>} and handling creation and
 * preparation of object instances.
 */
public final class PreferenceHelper$$InjectAdapter extends Binding<PreferenceHelper>
    implements Provider<PreferenceHelper> {
  private Binding<android.content.Context> context;

  public PreferenceHelper$$InjectAdapter() {
    super("com.paylogic.scanwarelite.helpers.PreferenceHelper", "members/com.paylogic.scanwarelite.helpers.PreferenceHelper", NOT_SINGLETON, PreferenceHelper.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    context = (Binding<android.content.Context>) linker.requestBinding("android.content.Context", PreferenceHelper.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(context);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<PreferenceHelper>}.
   */
  @Override
  public PreferenceHelper get() {
    PreferenceHelper result = new PreferenceHelper(context.get());
    return result;
  }

}
